[dependencies]
anyhow = "1.0.79"
chrono = "0.4.31"
env_logger = "0.10.1"
log = "0.4.20"
serde_toml = "0.0.1"
toml = "0.8.8"

[dependencies.clap]
features = ["cargo"]
version = "4.4.17"

[package]
authors = ["j-stach"]
edition = "2021"
license-file = "JLICENSE.md"
name = "jlic"
version = "0.1.0"

